version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat-service

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_stat_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stat-service
      - POSTGRES_USER=vlad
      - POSTGRES_PASSWORD=91735vladB!

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
